config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  get 'admin' => 'admin#home'

  devise_for :users, :controllers => { registrations: 'registrations' }

  resources :topics do
    member do
      post 'upvote'
    end
  end

  root 'static_pages#index'

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :recoverable, :rememberable,
         :trackable, :validatable
end

app/models/topic.rb
class Topic < ActiveRecord::Base
  has_many :votes, dependent: :destroy
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/vote.rb
class Vote < ActiveRecord::Base
  belongs_to :topic
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
	before_action :authenticate_admin!
  def home
  	@users = User.all
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private

  def sign_up_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation, :current_password)
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  before_action :authenticate_user, except: [:index]
  before_action :set_topic, only: [:show, :edit, :update, :destroy]

  # GET  /topics topics_path
  def index
  end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  #before_action :authenticate_admin!
  before_action :authenticate_user, except: [:index, :new, :edit, :create, :update, :upvote, :destroy]
  before_action :set_topic, only: [:show, :edit, :update, :destroy]

  # GET  /topics topics_path
  def index
    @topics = Topic.all
  end


  # GET  /topics/new  new_topic_path
  def new
    @topic = Topic.new
  end

  # GET  /topics/:id/edit  edit_topic_path
  def edit
  end

  # POST /topics
  def create
    @topic = Topic.new(topic_params)
    respond_to do |format|
      if @topic.save
        format.html { redirect_to action: "index" }
      else
        format.html { render :new }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /topics/:id
  def update
    respond_to do |format|
      if @topic.update(topic_params)
        format.html { redirect_to topics_path, notice: 'Topic was successfully updated.' }
        format.json { render :show, status: :ok, location: @topic }
      else
        format.html { render :edit }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE  /topics/:id
  def destroy
    @topic.destroy
    respond_to do |format|
      format.html { redirect_to topics_url, notice: 'Topic was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  # POST  upvote_topic  topics/:id/upvote
  def upvote
    @topic = Topic.find(params[:id])
    res = [0]
    @topic.votes.each do |vote|
      res << vote.created_at.strftime("%A, %b %d, %Y")
    end
    if res.last.to_s < Date.today.to_s(:heading_date)
      @topic.votes.create
    end
    redirect_to(topics_path)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_topic
      @topic = Topic.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def topic_params
      params.require(:topic).permit(:title, :description, :votes_attributes => [:topics_id])
    end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/admin/home.html.erb
<h1>Admin Dashboard</h1>
<ol>
  <% @users.each do |user| %>
    <h2><li><%= user.first_name %> <%= user.last_name %></li></h2>
  <% end %>
</ol>

app/views/layouts/_footer.html.erb
  <footer>
  	<hr />
    <div class="container" style="background-color: #aa8c75">
      <small>Ressie 2015&nbsp;&nbsp; | &nbsp;&nbsp;Jen Diamond - Kirk Chu - Kenny Lee - Thomas Lo</small>
    </div>
  </footer>

app/views/layouts/_header.html.erb
<header>
  Current user: <%= current_user.email %> </li>
</header>

app/views/layouts/_messages.html.erb
<div style="width:40%; padding 5 10 10 20px; margin: 0 auto;">
  <% flash.each do |name, msg| %>
    <% if msg.is_a?(String) %>

      <div class="alert alert-<%= name.to_s == "notice" ? "success" : "danger" %>">
        <a class="close" data-dismiss="alert">&#215;</a>
        <%= content_tag :div, msg, :id => "flash_#{name}" %>
      </div>

    <% end %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Suggestotron</title>
  <link rel="stylesheet" href="//railsgirls.com/assets/bootstrap.css">
  <link rel="stylesheet" href="//railsgirls.com/assets/bootstrap-theme.css">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link rel="stylesheet" type="text/css" href="http://fonts.googleapis.com/css?family=Cabin+Sketch">
</head>
<body>
  <div class="navbar">
    <ul class="hmenu">
      <%= render 'devise/menu/registration_items' %>
      <%= render 'devise/menu/login_items' %>
    </ul>
  </div>
  <div class="container">
    <%= render 'layouts/messages' %>
    <%= yield %>
  </div>

  <%= render 'layouts/footer' %>

  <script src="//railsgirls.com/assets/bootstrap.js"></script>
</body>
</html>

app/views/static_pages/index.html.erb
<h1>Create a Ressie! </h1>

<h2>Update them everyday to track your progress this year.</h2>

<br />

<%= button_to 'Start here!', topics_path, method: :get, :class => "btn btn-success btn-size" %>

app/views/topics/_form.html.erb
<%= form_for(@topic) do |f| %>
  <% if @topic.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@topic.errors.count, "error") %> prohibited this topic from being saved:</h2>

      <ul>
      <% @topic.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/topics/edit.html.erb
<h2 class="new-ressie">Edit your Resolution</h2>

<%= render 'form' %>

<%= link_to 'Delete', @topic, method: :delete, data: { confirm: 'Are you sure?' } %>
<%= link_to 'Back', topics_path %>

app/views/topics/index.html.erb
<% if current_user %>
   <%= button_to "Log out", destroy_user_session_path, method: :delete, :class => "btn btn btn-danger btn-top" %>
<% else %>
  <%= button_to "Log in", new_user_session_path, method: :get, :class => "btn btn-primary btn-top" %>
  <%= button_to "Sign up", new_user_registration_path, method: :get, :class => "btn btn-warning btn-top" %>
<% end %>

<hr />

<h1 class="new-ressie"><%= link_to 'Create a New Ressie', new_topic_path, :class => "new-ressie" %></h1>
<h3 style="color: #79c754; line-height: 30%;">It's <%= Date.today.to_s(:heading_date) %></h3>
<h2 style="line-height: 30%;"><%= "#{current_user.first_name} #{current_user.last_name}," if current_user %></h2>
<h2 style="line-height: 30%;">Did you honor your</h2> 
<h2 style="line-height: 30%;">resolutions today?</h2>
<br/>
<div>
  <% @topics.each do |topic| %>
    <div>
      <%= button_to upvote_topic_path(topic),
          method: :post, :class => "btn btn-success btn-size" do %>

       <h3><%= "#{topic.title}" %></h3>

      <% res=[0] %>
      <% topic.votes.each do |vote| %>
        <% res << "#{vote.created_at.strftime("%A, %b %d, %Y %H:%M:%S")}" %>
      <% end %>
    <hr/>
      <h6><%= "Last upvote: #{res.last}" %></h6>

     <hr/>
        <h3 style = "color: #98ddde;"><%= "#{topic.votes.count} success days!" %></h3>

        <i class="fa fa-pencil"></i>&nbsp;<%= link_to 'Edit', edit_topic_path(topic) %>
      <% end %>
      </div>
      <br/>
  <% end %>
</div>

app/views/topics/new.html.erb
<h1>New Resolution</h1>

<%= render 'form' %>

<%= link_to 'Back', topics_path %>